// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SyncDocumentProto {
    #[prost(string, tag = "1")]
    pub doc_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub version: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OperationProto {
    #[prost(string, tag = "5")]
    pub doc_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub new_content: ::prost::alloc::string::String,
    #[prost(uint32, tag = "7")]
    pub client_version: u32,
}
