// This file is @generated by prost-build.
/// Represents a full document state for synchronization.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SyncDocumentProto {
    #[prost(string, tag = "1")]
    pub doc_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub version: u64,
}
/// Defines an insertion operation.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InsertOp {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub client_version: u64,
}
/// Defines a deletion operation.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteOp {
    #[prost(uint32, tag = "1")]
    pub start: u32,
    #[prost(uint32, tag = "2")]
    pub end: u32,
    #[prost(string, tag = "3")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub client_version: u64,
}
/// Defines a replacement operation (delete then insert).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplaceOp {
    #[prost(uint32, tag = "1")]
    pub start: u32,
    #[prost(uint32, tag = "2")]
    pub end: u32,
    #[prost(string, tag = "3")]
    pub text: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub client_version: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Noop {
    #[prost(string, tag = "1")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub client_version: u64,
}
/// Represents a single collaborative editing operation.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OperationProto {
    #[prost(uint64, tag = "1")]
    pub op_id: u64,
    /// Metadata related to the operation's source and state.
    #[prost(string, tag = "6")]
    pub doc_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "8")]
    pub client_version: u64,
    #[prost(uint64, tag = "9")]
    pub server_version: u64,
    #[prost(string, tag = "10")]
    pub new_content: ::prost::alloc::string::String,
    #[prost(oneof = "operation_proto::Kind", tags = "2, 3, 4, 5")]
    pub kind: ::core::option::Option<operation_proto::Kind>,
}
/// Nested message and enum types in `OperationProto`.
pub mod operation_proto {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "2")]
        Insert(super::InsertOp),
        #[prost(message, tag = "3")]
        Delete(super::DeleteOp),
        #[prost(message, tag = "4")]
        Replace(super::ReplaceOp),
        #[prost(message, tag = "5")]
        Noop(super::Noop),
    }
}
